version: '3.4'

services:
  hermesstream.notification.api:
    image: ${DOCKER_REGISTRY-}hermesstreamnotificationapi
    build:
      context: .
      dockerfile: HermesStream.Notification.Api/Dockerfile
  rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports: 
             - 5672
             - 15672
        volumes:
             -  ./data:/var/lib/rabbitmq/
        environment:
             - RABBITMQ_DEFAULT_USER=admin
             - RABBITMQ_DEFAULT_PASS=123456