name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "390853331" | docker login -u "juliaasoares" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t juliaasoares/hermesstreamnotificationapi:1.0.0 ./HermesStream.Notification.Api 
          docker push juliaasoares/hermesstreamnotificationapi:1.0.0
